MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data.

[Writable]
LogLevel = "INFO"

[Service]
Port = 59983 # Device services are assigned to the 599xx range
StartupMsg = "device-usb-camera started"

[MessageBus]
  [MessageBus.Optional]
  # Default MQTT and NATS Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-usb-camera"

[Device]
# TODO: Uncomment this in PR to use built in loading of Provision Watchers and remove custom ProvisionWatcherDir below
#ProvisionWatchersDir = "./res/provision_watchers"
  [Device.Discovery]
  Enabled = true
  Interval = "1h"

[Driver]
RtspServerHostName = "localhost"
RtspTcpPort = "8554"
# The location of Provision Watcher json files to import when using auto-discovery
ProvisionWatcherDir = "res/provision_watchers"
